In [1]:
import pandas as pd
import datetime

In [2]:
rawdata = pd.read_csv('synthetic_5g_kpis.csv',sep=',')

In [3]:
rawdata

,time,cell_id,user_id,slice_id,throughput_dl_mbps,throughput_ul_mbps,latency_ms,jitter_ms,packet_loss_pct
0,2025-11-07 10:00:00,cell_01,UE_030,eMBB,62.025775,22.145384,5.838731,0.651401,0.468226
1,2025-11-07 10:00:00,cell_01,UE_016,eMBB,63.844322,13.599499,14.238017,0.823548,0.708354
2,2025-11-07 10:00:00,cell_01,UE_025,eMBB,58.321120,17.440078,11.879174,2.010462,0.470640
3,2025-11-07 10:00:00,cell_01,UE_018,eMBB,40.480508,15.945957,11.630914,1.381730,0.682955
4,2025-11-07 10:00:00,cell_01,UE_009,eMBB,75.772564,20.560936,9.802281,1.323846,0.448923
...,...,...,...,...,...,...,...,...,...
21595,2025-11-07 21:59:00,cell_03,UE_024,eMBB,62.781487,12.957871,12.026586,0.918365,0.469858
21596,2025-11-07 21:59:00,cell_03,UE_027,eMBB,84.640630,28.218208,10.102953,2.111094,0.657434
21597,2025-11-07 21:59:00,cell_03,UE_022,eMBB,78.123235,20.672146,11.149561,2.166082,0.658113
21598,2025-11-07 21:59:00,cell_03,UE_029,eMBB,77.561408,24.661195,13.711037,0.325656,0.498395
21599,2025-11-07 21:59:00,cell_03,UE_002,eMBB,78.506598,19.688669,10.845902,0.125325,0.602360

In [4]:
rawdata['time'] = pd.date_range(start='2025-11-07 10:00:00', periods=len(rawdata), freq='s')

In [5]:
rawdata.set_index(rawdata['time'], inplace = True)

In [6]:
rawdata

,time,cell_id,user_id,slice_id,throughput_dl_mbps,throughput_ul_mbps,latency_ms,jitter_ms,packet_loss_pct
time,,,,,,,,,
2025-11-07 10:00:00,2025-11-07 10:00:00,cell_01,UE_030,eMBB,62.025775,22.145384,5.838731,0.651401,0.468226
2025-11-07 10:00:01,2025-11-07 10:00:01,cell_01,UE_016,eMBB,63.844322,13.599499,14.238017,0.823548,0.708354
2025-11-07 10:00:02,2025-11-07 10:00:02,cell_01,UE_025,eMBB,58.321120,17.440078,11.879174,2.010462,0.470640
2025-11-07 10:00:03,2025-11-07 10:00:03,cell_01,UE_018,eMBB,40.480508,15.945957,11.630914,1.381730,0.682955
2025-11-07 10:00:04,2025-11-07 10:00:04,cell_01,UE_009,eMBB,75.772564,20.560936,9.802281,1.323846,0.448923
...,...,...,...,...,...,...,...,...,...
2025-11-07 15:59:55,2025-11-07 15:59:55,cell_03,UE_024,eMBB,62.781487,12.957871,12.026586,0.918365,0.469858
2025-11-07 15:59:56,2025-11-07 15:59:56,cell_03,UE_027,eMBB,84.640630,28.218208,10.102953,2.111094,0.657434
2025-11-07 15:59:57,2025-11-07 15:59:57,cell_03,UE_022,eMBB,78.123235,20.672146,11.149561,2.166082,0.658113
2025-11-07 15:59:58,2025-11-07 15:59:58,cell_03,UE_029,eMBB,77.561408,24.661195,13.711037,0.325656,0.498395
2025-11-07 15:59:59,2025-11-07 15:59:59,cell_03,UE_002,eMBB,78.506598,19.688669,10.845902,0.125325,0.602360

In [8]:
from influxdb_client import InfluxDBClient

In [9]:
my_token="ScI05S9QOAto2fUFU--qGOP5dvUEFLZhw3DT1NY6DsLqnig6cqjKW-Ol45Zg71nXCqugm4L_cV-qnBIQMlhZWg=="

In [11]:
client = InfluxDBClient(url="http://localhost:8086", token=my_token, org="Somorrostro")

In [12]:
write_client = client.write_api()

In [13]:
write_client.write(
    bucket="prueba5g-bucket",
    record=rawdata,
    data_frame_measurement_name="datos-sinteticos5g",
    data_frame_tag_columns=["cell_id", "user_id", "slice_id"]
)

The retriable error occurred during request. Reason: 'HTTPConnection(host='localhost', port=8086): Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'.
The retriable error occurred during request. Reason: 'HTTPConnection(host='localhost', port=8086): Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'.
The retriable error occurred during request. Reason: 'HTTPConnection(host='localhost', port=8086): Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'.
The retriable error occurred during request. Reason: 'HTTPConnection(host='localhost', port=8086): Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'.
The retriable error occurred during request. Reason: 'HTTPConnection(host='localhost', port=8086): Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'.
The batch item wasn't processed successfully because: HTTPConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /api/v2/write?org=Somorrostro&bucket=prueba5g-bucket&precision=ns (Caused by NewConnectionError("HTTPConnection(host='localhost', port=8086): Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión"))
The retriable error occurred during request. Reason: 'HTTPConnection(host='localhost', port=8086): Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'.
The retriable error occurred during request. Reason: 'HTTPConnection(host='localhost', port=8086): Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'.
The retriable error occurred during request. Reason: 'HTTPConnection(host='localhost', port=8086): Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'.
The retriable error occurred during request. Reason: 'HTTPConnection(host='localhost', port=8086): Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'.
The retriable error occurred during request. Reason: 'HTTPConnection(host='localhost', port=8086): Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión'.